name: Remove Git Submodule

on:
  workflow_dispatch:
  # push: { branches: ["main"] }

permissions:
  contents: write

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Remove previous screenshot
      run: rm -rf artifact
    - name: Commit the removal
      uses: stefanzweifel/git-auto-commit-action@v5
