name: Take Website Screenshot

on:
  workflow_dispatch:
  # push: { branches: ["main"] }

permissions:
  contents: write

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
    #   with:
    #     fetch-depth: 0

    - name: Delete screenshot
      run: rm -f screenshot.png

    - name: Display structure of downloaded files again
      run: ls -R

    - name: Take Screenshot
      uses: karol-brejna-i/webpage-screenshot-action@v1
      with:
        url: https://semanticdata.github.io/bamboo/
        output: screenshot.png

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     path: screenshot.png

    # - name: Download artifact
    #   uses: actions/download-artifact@v4

    - name: Display structure of downloaded files
      run: ls -R

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Commit from screenshot workflow
    #     push_options: '--force'
