name: Take Website Screenshot

on:
  workflow_dispatch:
  # push: { branches: ["main"] }

permissions:
  contents: write
  # id-token: write

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Take Screenshot
      uses: karol-brejna-i/webpage-screenshot-action@v1
      with:
        url: https://semanticdata.github.io/bamboo/
        output: screenshot.png
    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Commit from screenshot workflow
    - name: Display structure of downloaded files
      run: ls -R
