name: Take Website Screenshot

on:
  workflow_dispatch:
  # push: { branches: ["main"] }

permissions:
  contents: write
  id-token: write

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
    - name: Take Screenshot
      id: screenshot
      uses: karol-brejna-i/webpage-screenshot-action@v1
      with:
        url: https://semanticdata.github.io/bamboo/
    - name: Commit screenshot
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Changed files via GitHub Actions
    # - name: Copy Screenshot
    #   run: cp ${{ steps.screenshot.outputs.path }} .
    - name: Display structure of downloaded files
      run: ls -R
