name: Take Website Screenshot

on:
  workflow_dispatch:
  # push: { branches: ["main"] }

permissions:
  contents: write
  pages: write

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
    - name: Screenshot Website
      uses: swinton/screenshot-website@main
      with:
        source: https://semanticdata.github.io/bamboo/
        destination: screenshot.png
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: screenshot.png
    - name: Download created artifact
      uses: actions/download-artifact@v4
    # - name: Copy Screenshot
    #   run: cp ${{ steps.screenshot.outputs.path }}/ ./
    - name: Display structure of downloaded files
      run: ls -R
