# Source: https://github.com/lowlighter/metrics#-documentation
name: Update Website Screenshot (new)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics-screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: screenshot.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          base: ""
          plugin_screenshot: yes
          plugin_screenshot_title: Screenshot - Bamboo CSS
          plugin_screenshot_url: https://semanticdata.github.io/bamboo/readme.html
          plugin_screenshot_selector: body # default
          plugin_screenshot_background: no # changed
          plugin_screenshot_wait:        0 # default
          plugin_screenshot_viewport: '{"width": 1280, "height": 1280}' # default: 1280x1280
